### ISSUE TITLE
How to hide left panel on mobile devices?

### ISSUE THREAD

**Issue by diegolyanky** [Tinyportal/TinyPortal#851] opened 2021-04-17 14:50 UTC
Hi all... is there a way to hide left panel when an user is over a mobile device?

Thanks!

**Comment by Bopske** [comment] 2021-04-18 16:24
Nope, sorry this is not a bug but a feature request. I will close this here. Feel free to request features on the TinyPortal support site...

**Closed as completed by Bopske** 2021-04-18 16:24 UTC
