### ISSUE TITLE
Non admin accessing My articles : "Unable to load the 'main' template."

### ISSUE THREAD

**Issue by Bopske** [Tinyportal/TinyPortal#504] opened 2019-12-06 19:54 UTC
See this:

https://www.tinyportal.net/index.php?topic=36303.msg298336#msg298336

Just tried to reproduce this in one of my test forums (on TP200) and when the test-user access the menu option: Tinyportal > My Articles I get the error:

"Unable to load the 'main' template."

**Comment by tinoest** [comment] 2019-12-19 15:46
Duplicate of #491

**Closed as completed by tinoest** 2019-12-19 15:46 UTC
